### ISSUE TITLE
Congratulations 

### ISSUE THREAD

**Issue by snoby** [heaje/hiveos-exporter#2]
Thank you for this work, I think you should post on the read me your ethereum or bitcoin wallet address for donations.  I would definitely like to thank you for the work you have done here.

**Comment by heaje** [comment]
Thanks @snoby!  I really appreciate it.  I just got them added.

**Comment by snoby** [comment]
> Thanks @snoby! I really appreciate it. I just got them added.

@heaje  - Sent you some gas money on ETH.  You've done a really great job here.  Hit me up on discord iotapi322#9019
Would love to bring you in on a group of like minded miners.
